# Generated by Django 4.1.7 on 2023-03-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('access_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WelfareActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_participants', models.IntegerField()),
                ('dates', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.benefits')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(max_length=20)),
                ('asked_date', models.DateField(max_length=20)),
                ('manager_perm', models.BooleanField()),
                ('hr_perm', models.BooleanField()),
                ('finance_perm', models.BooleanField()),
                ('happy_hour_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='happy_hour', to='sababa.welfareactivity')),
                ('orderer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.employee')),
                ('welfare_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.welfareactivity')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sababa.events')),
            ],
        ),
    ]
