# Generated by Django 4.1.7 on 2023-04-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sababa', '0003_alter_happyhour_description_user_invitedgifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
