# Generated by Django 4.1.7 on 2023-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sababa', '0007_rename_preferredbenefits_chosenbenefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareactivity',
            name='reason',
            field=models.CharField(default='No reason added', max_length=256),
        ),
    ]
