# Generated by Django 4.1.7 on 2023-05-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sababa', '0008_welfareactivity_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='InvitedGifts',
            new_name='OrderedGifts',
        ),
        migrations.RenameField(
            model_name='orderedgifts',
            old_name='invitation_id',
            new_name='order_id',
        ),
    ]
