# Generated by Django 4.1.7 on 2023-05-09 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sababa', '0009_rename_invitation_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfareactivity',
            name='dates',
        ),
        migrations.AddField(
            model_name='welfareactivity',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='type',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('HOLIDAY', 'Holiday')], max_length=8),
        ),
    ]
